/*
-- Query: SELECT * FROM hciproject.blog
LIMIT 0, 1000

-- Date: 2019-02-06 13:33
*/
INSERT INTO `blog` (`id`,`category`,`com_number`,`date`,`image`,`likes`,`photo1`,`photo2`,`photo3`,`text`,`title`,`username`,`view`,`small_text`) VALUES (113,'Nature',0,'2019-01-23 19:43:31',NULL,1,'images.jpg',NULL,NULL,'Toktogul Reservoir was formed in 1976 by a Soviet-built dam across the Naryn River. The reservoir is long and narrow and is the largest in Central Asia (284 square kilometers, averaging 215 meters in depth). Highway M41 (Central Asia Pamir Highway) follows the northeast and southern shores, from the town of Toktogul (where the Chychkan River empties into the reservoir) to the dam near Kara Kol.\r\nWhile driving along the south side of the reservoir, the views to the north are sublime. Turquoise green water reflects rugged mountains with reddish and purple rock strata. There are several pullouts along the road where one can follow a dirt track to the lake shore for a hike, picnic, swimming or fishing (carp, pike, and trout). All of these activities are available at the town of Toktogul where there are guesthouses, restaurants, cafes and horses for rent. At the other end of the reservoir, a concrete dam 215 meters high generates 1,200 MW of electricity, supplying the area with power. GE Hydro and GE Renewables recently announced a project to expand the generating capacity to 1440 MW. Some of the power and water goes to neighboring Uzbekistan.','Toktogul city','nadyr.sultanov@gmail.com',13,'Toktogul Reservoir was formed in 1976 by a Soviet-built dam across the Naryn River. The reservoir is...');
INSERT INTO `blog` (`id`,`category`,`com_number`,`date`,`image`,`likes`,`photo1`,`photo2`,`photo3`,`text`,`title`,`username`,`view`,`small_text`) VALUES (114,'Culture',2,'2019-01-23 19:42:05',NULL,0,'im.jpg',NULL,NULL,'This five-peaked rocky crag seems to loom above the city wherever you go. It has been a Muslim place of pilgrimage for centuries, supposedly because the Prophet Mohammed once prayed here. Its slopes are indented with many a cave and crevice each reputed to have different curative or spiritual properties; many are detailed on photo-boards in the Cave Museum. One such is fertility mini-cave Ene-Beshik, its rocks worn smooth by young women slithering in to aid their motherly aspirations.','Sulaiman-Too','zyndanbaeva.97@gmail.com',13,'This five-peaked rocky crag seems to loom above the city wherever you go. It has been a Muslim place...');
INSERT INTO `blog` (`id`,`category`,`com_number`,`date`,`image`,`likes`,`photo1`,`photo2`,`photo3`,`text`,`title`,`username`,`view`,`small_text`) VALUES (115,'Nature',0,'2018-12-04 23:14:41',NULL,0,'immm.jpeg',NULL,NULL,'Sary-Chelek is an alpine lake, the largest in the western Tien Shan and the nature reserve. It is located at an altitude of 1940 meters in the western part of the Jalal-Abad Region.\r\nSary-Chelek is a landslide lake. It was formed about 10,000 years ago after a powerful earthquake that overwhelmed the valley with the river flowing in it. The area of the lake is about 50 square kilometers and in length, it stretched for 7.5 kilometers. The first thing that catches your eye is the amazing clarity of the transparency of the water in Sary Chelek. This is a big rarity for the Tien-Shan Lakes – usually in mountain lakes the water is opaque due to a large amount of mineral impurities. Sary-Chelek is an exception. Sary-Chelek is the second deepest lake in Kyrgyzstan and the third in Central Asia. Its depth in some places reaches 234 meters and due to this fact the lake does not warm up more than 20 degrees in summer and in winter it barely cools down to 0.','Sary-Chelek','iman@gmail.com',0,NULL);
