/*
-- Query: SELECT * FROM hciproject.place
LIMIT 0, 1000

-- Date: 2019-02-06 13:39
*/
INSERT INTO `place` (`id`,`address`,`category`,`com_number`,`date`,`image`,`likes`,`photo1`,`photo2`,`photo3`,`text`,`title`,`usarname`,`view`,`small_text`) VALUES (8,'Toktogul','Nature',4,'2018-12-09 23:20:28',NULL,1,'ddd.jpg','toktogul-dam.jpg',NULL,'\r\nToktogul, named after Kyrgyzstan’s most famous akyn, Toktogul Satylganov, is an unassuming, pleasant place to wander. It’s a good place to break the journey between Osh and Bishkek, with a pretty location between lake and mountains. It can also be used as a hiking hub towards Suusamyr, Arslanbob and Sary-Chelek, all 3-4 days out, with more options for outdoor activities closer to the town.','Toktogul city','tansuluu.myrzaeva@iaau.edu.kg',15,'\r\nToktogul, named after Kyrgyzstan’s most famous akyn, Toktogul Satylganov, is an unassuming, pleasa...');
INSERT INTO `place` (`id`,`address`,`category`,`com_number`,`date`,`image`,`likes`,`photo1`,`photo2`,`photo3`,`text`,`title`,`usarname`,`view`,`small_text`) VALUES (9,'Osh','Culture',3,'2019-02-06 13:24:29',NULL,0,'998.jpg','mountain-sulaiman-too.jpg',NULL,'Sulaiman-Too Sacred Mountain Kyrgyzstan dominates the Fergana Valley and forms the backdrop to the city of Osh, at the crossroads of important routes on the Central Asian Silk Roads. For more than one and a half millennia, Sulaiman was a beacon for travellers revered as a sacred mountain. Its five peaks and slopes contain numerous ancient places of worship and caves with petroglyphs as well as two largely reconstructed 16th century mosques. One hundred and one sites with petroglyphs representing humans and animals as well as geometrical forms have been indexed in the property so far. The site numbers 17 places of worship, which are still in use, and many that are not. Dispersed around the mountain peaks they are connected by footpaths. The cult sites are believed to provide cures for barrenness, headaches, and back pain and give the blessing of longevity. Veneration for the mountain blends pre-Islamic and Islamic beliefs. ','Sulaiman-Too','tansuluu.myrzaeva@iaau.edu.kg',15,'Sulaiman-Too Sacred Mountain Kyrgyzstan dominates the Fergana Valley and forms the backdrop to the c...');
INSERT INTO `place` (`id`,`address`,`category`,`com_number`,`date`,`image`,`likes`,`photo1`,`photo2`,`photo3`,`text`,`title`,`usarname`,`view`,`small_text`) VALUES (103,'Jalal-Abad','Nature',1,'2018-12-19 11:12:15',NULL,0,'lakeofsarychelek3.jpg','IMG_20180718_235330_903.jpg',NULL,'The lake and surrounding Biosphere Reserve of Sary-Chelek are oft-quoted as one of the most beautiful sights in Kyrgyzstan. A habitat for 1.000 different plants and rare mammals such as bear and lynx, Sary-Chelek is a great place to hike, observe nature or to simply get away from it all.','Sary-Chelek','nadyr.sultanov@gmail.com',19,'The lake and surrounding Biosphere Reserve of Sary-Chelek are oft-quoted as one of the most beautifu...');
