/*
-- Query: SELECT * FROM hciproject.user
LIMIT 0, 1000

-- Date: 2019-02-06 13:41
*/
INSERT INTO `user` (`user_id`,`about_me`,`active`,`age`,`country`,`email`,`experience`,`gender`,`image`,`languages`,`name`,`password`,`status`,`token`) VALUES (5,'I am from Almaty. I wanna visit Kyrgyzstan first time so I need A gid for my trip. I hope here I can find friends.',1,'21','Qazaqstan','zyndanbaeva.97@gmail.com','','female','avatar6.png','Russian, English, Kazah','Suleimenova Diana','$2a$10$ofDlPXgMniiccG4OvMRkT.KMtuNmh6vv7k1khmj7b4ab5zz1Kid5y','tourist',NULL);
INSERT INTO `user` (`user_id`,`about_me`,`active`,`age`,`country`,`email`,`experience`,`gender`,`image`,`languages`,`name`,`password`,`status`,`token`) VALUES (4,'I am from Toktogul.Nowadays I live and study in Bishkek. Love travelling.',1,'22','Kyrgyzstan','tansuluu.myrzaeva@iaau.edu.kg','2','female','download.jpg','Russian, English, Kyrgyz','Myrzaeva Tansuluu','$2a$10$BXB8iOoQHL2ZwhaCu/ktEec2sKu0Wqqwwh5Pv5Q1aqQRNHNQbFHHa','gid','dd228b8d-8568-4b5c-a1f0-7a963e738cc3');
INSERT INTO `user` (`user_id`,`about_me`,`active`,`age`,`country`,`email`,`experience`,`gender`,`image`,`languages`,`name`,`password`,`status`,`token`) VALUES (100,'I am from Bishkek. I know a lot of local places. So choose me please!',1,'21','Kyrgyzstan','nadyr.sultanov@gmail.com','3','male','XY3qvsyuJVc.jpg','Russian, English, Kyrgyz','Nadyr Sultanov','$2a$10$jjBmXQh5OYNq5SCauU4ba.a7HaliQUTW/CQJzdT.FTHz2yoFIIA7K','gid',NULL);
INSERT INTO `user` (`user_id`,`about_me`,`active`,`age`,`country`,`email`,`experience`,`gender`,`image`,`languages`,`name`,`password`,`status`,`token`) VALUES (101,'I am from Russia. Wanna visit Bishkek and find out local life, and get a lot of experiences.',1,'22','Russia','iman@gmail.com','','female','image.jpg','Russian, English','Nurdin Imanaliev','$2a$10$VPaK4u7CYxByrmdWGM19Gu2jsdSrWRnSY9h3QBvqM5lx5uEtEaF26','tourist',NULL);
INSERT INTO `user` (`user_id`,`about_me`,`active`,`age`,`country`,`email`,`experience`,`gender`,`image`,`languages`,`name`,`password`,`status`,`token`) VALUES (104,'I am from Tokmok. I know a lot beautiful places in our country.Welcome to Kyrgyzstan!',1,'22','Kyrgyzstan','medyz@gmail.com','2','male','med.jpg','Russian, English, Kyrgyz','Meder Abdyldaev','$2a$10$N7V2BkCr9ei8aqaBqywicuLgw.QdHl/C50DJlLlSRTtEWy8.J82p2','gid',NULL);
INSERT INTO `user` (`user_id`,`about_me`,`active`,`age`,`country`,`email`,`experience`,`gender`,`image`,`languages`,`name`,`password`,`status`,`token`) VALUES (110,'I wanna visit Central Asia first time. At the start I gonna visit Kyrgyzstan',1,'10','USA','asema@gmail.com','','female','member.png','Russian,  Kyrgyz','Asema Zyndanbaeva','$2a$10$.nTGpGrq20xYBktCmRYix.Q8jT.m45o0sf73sCkJG/TT5h8vW69pa','tourist',NULL);
INSERT INTO `user` (`user_id`,`about_me`,`active`,`age`,`country`,`email`,`experience`,`gender`,`image`,`languages`,`name`,`password`,`status`,`token`) VALUES (111,'I have visited a lot of places in our country, such as Naryn, Talas, Osh. So I may guide you.',1,'21','Kyrgyzstan','aidana@gmail.com','4','female','member.png','Russian, English, Kyrgyz','Suleimenova Aidana','$2a$10$Wsurcoh5MxEqGUDMrGQKJe.HNxPKSqoJi4Kr2UvTDXZsiKO5wZdEi','gid',NULL);
INSERT INTO `user` (`user_id`,`about_me`,`active`,`age`,`country`,`email`,`experience`,`gender`,`image`,`languages`,`name`,`password`,`status`,`token`) VALUES (124,'One way the engineer can keep track of the relationship between requirements is through a requirements verification document.  This document includes all requirements and has the procedures that will go into validating each one is correct.  A requirements matrix within this document would show how the requirements relate to each other.',1,'21','Kyrgyzstan','imasn@gmail.com','2','female','member.png','Russian, English, Kyrgyz','Myrzaeva Tansuluu','$2a$10$yAaZNSZzliLd2wqfkrGsL.RPjCjGsNS0q3yelIssHKA6JtrplPjum','gid',NULL);
INSERT INTO `user` (`user_id`,`about_me`,`active`,`age`,`country`,`email`,`experience`,`gender`,`image`,`languages`,`name`,`password`,`status`,`token`) VALUES (127,'I am hfeo kfddgoi sfmeojgn  vijgedimv',1,'33','Kyrgyzstan','tansuluu.myrzaea@iaau.edu.kg','5','female','member.png','Russian, English, Kyrgyz','Myrzaeva Tansuluu','$2a$10$BncuGnX30TlGH278x3S94eiehBYDFxzl1QrcGv/16yjw2JEaGWez.','gid',NULL);
